### ISSUE TITLE
uint64 coin amount limit on `peggy tx bank send ...` transaction

### ISSUE THREAD

**Issue by michaelfig** [althea-net/cosmos-gravity-bridge#166] opened 2021-01-20 18:48 UTC
I pinged @jkilpatr and @jackzampolin on Discord#althea-validators:

> When prepping for the Agoric demo (Eth->Peggy->IBC), we noticed that for ERC-20 that has 18 decimals, we could not even send 300 units (300 * 10 ** 18) on-chain between two peggy accounts.  Something about int64 being too small for the coin quantity.  We could transfer 300 from Eth to Peggy and query that balance from Peggy, but after that, had to move it in smaller batches or the transaction would be rejected by the Peggy chain.

@jkilpatr replied:

> coin amounts are bigints though?
> must be a u64 somewhere

Yeah, probably somewhere in the Cosmos SDK.

> and by on chain do you mean with normal tx commands or using any of the bridge utilities?

I mean with the normal `peggy tx bank send ...` command.  I don't have my environment running right now to describe the error any better, but the chain rejected the transaction.

I had a similar error when trying `rly raw tx send ...` to convey the same amount over IBC transfer.

**Comment by jtremback** [comment] 2021-01-21 23:56
@fedekunze I think you're most familiar with the SDK, right? I thought that our whole code path was all BigInts but maybe I'm wrong.

Either way I think we should include some tests which use a realistic amount of tokens.

**Comment by jkilpatr** [comment] 2021-01-26 00:03
Good call I'll add this to my testing schedule.

**Comment by jkilpatr** [comment] 2021-02-11 18:22
@michaelfig  I can't seem to reproduce this. I have a few tests moving 1*10^18 wei of tokens around.

**Comment by michaelfig** [comment] 2021-02-11 19:17
> I have a few tests moving 1*10^18 wei of tokens around.

That's still less than 2^64.  Please try with 20*10^18.  My tests were with 300*10^18.

**Comment by jtremback** [comment] 2021-02-25 16:40
Fixed by indexing on uints properly by padding to 32 bytes, since sdk and eth ints are limited to 32 bytes anyway

**Closed by jtremback** 2021-02-25 16:40 UTC
